
[functions.delete-business]
enabled = true
verify_jwt = true
import_map = "./functions/delete-business/deno.json"
entrypoint = "./functions/delete-business/index.ts"

[functions.send-otp]
enabled = true
verify_jwt = false
import_map = "./functions/import_map.json"
entrypoint = "./functions/send-otp/index.ts"

[functions.verify-otp]
enabled = true
verify_jwt = false
import_map = "./functions/import_map.json"
entrypoint = "./functions/verify-otp/index.ts"

